#!/usr/bin/env bash

set -euo pipefail

if command -v git >/dev/null 2>&1 && [ "$(git config -f ~/.config/git/config include.path)" != "config.main" ]; then
    rm -f ~/.config/git/config
    touch ~/.config/git/config
    git config -f ~/.config/git/config include.path config.main
fi
