#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd -P)
sourcedir=$(dirname "$scriptdir")

if ! [ -e "$sourcedir/.chezmoiroot" ]; then
    sourcedir=
fi

chezmoi init --apply ${sourcedir:+--source "$sourcedir"} kergoth/dotfiles-chezmoi
