#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd -P)
sourcedir=$(dirname "$scriptdir")
PATH="$PATH:$scriptdir:$sourcedir/scripts"

sudo chown -R "$USER" "$HOME"

bootstrap
