#!/usr/bin/env bash

repodir="$(dirname "$(cd "$(dirname "$0")" && pwd -P)")"
PATH="$repodir/scripts:$repodir/scripts:$HOME/.local/bin:$PATH"

# shellcheck source=../scripts/common.sh
. "$repodir/scripts/common.sh" || exit 1

set -euo pipefail

if [ "$(id -u)" = "0" ]; then
    die "Error: Do not run as root, this script is for user setup"
fi

if command -v "setup-user-$OS" &>/dev/null; then
    msg "Running setup-user-$OS"
    "setup-user-$OS"
else
    msg "No setup-user-$OS script found, skipping"
fi

if command -v "setup-user-$SYSTEM" &>/dev/null; then
    msg "Running setup-user-$SYSTEM"
    "setup-user-$SYSTEM"
else
    msg "No setup-user-$SYSTEM script found, skipping"
fi

# component_source "$repodir" pre-setup

# msg "Initializing and applying dotfiles"
# if ! command -v chezmoi &>/dev/null; then
#     (cd ~ && sh -c "$(curl -fsLS get.chezmoi.io/lb)")
# fi
# chezmoi init "--source=$HOME/.local/share/chezmoi" kergoth/dotfiles-chezmoi
# chezmoi apply

# component_source "$repodir" setup
# component_source "$repodir" post-setup

msg "User setup complete"
